title: PyBugHive
description: A Comprehensive Database of Manually Validated, Reproducible Python Bugs
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
bugs: 149
projects: 11
github_link: https://github.com/pybughive
pdf_link: https://ieeexplore.ieee.org/abstract/document/10644000/
download_link: download.html
details_link: details.html
home_link: /
